Ansible managed, add mysql streaming backup and error handling

diff --git a/templates/borg-backup.sh.j2 b/templates/borg-backup.sh.j2
--- a/templates/borg-backup.sh.j2
+++ b/templates/borg-backup.sh.j2
@@ -1,5 +1,9 @@
 #!{{ borgbackup_shell }}
 
+##
+## {{ ansible_managed }}
+## 
+
 if [ -z "$1" ] || [ ! -z "$2" ]
   then
     printf "Possible: info | init | list | backup | mount \n\n"
@@ -62,18 +66,40 @@ if [ "$1" = "backup" ]
     {{ precommand }}
 {% endfor %}
 
+# Create array for exit codes
+BORGEXIT=()
 {% for b in borgbackup_servers %}
     printf "Backing up to {{ b.fqdn }} :\n"
     REPOSITORY={% if b.type == 'hetzner' %}ssh://{% endif %}{{ b.user }}@{{ b.fqdn }}:{% if b.type == 'hetzner' %}23/./{% endif %}{{ b.home }}{{ b.pool }}/{{ inventory_hostname }}
     
-    /usr/local/bin/borg create --progress --compression {{ borgbackup_compression }} --stats {{ b.options }} $REPOSITORY::$date {% for dir in borgbackup_include %}{{ dir }} {% endfor %}{% if automysql.stat.isdir is defined and automysql.stat.isdir == True %}/var/lib/automysqlbackup{% endif %} {% for dir in borgbackup_exclude %} --exclude '{{ dir }}'{% endfor %}
+    /usr/local/bin/borg create --progress --compression {{ borgbackup_compression }} --stats {{ b.options }} $REPOSITORY::$date {% for dir in borgbackup_include %}{{ dir }} {% endfor %}{% if automysql.stat.isdir is defined and automysql.stat.isdir == True %}/var/lib/automysqlbackup{% endif %} {% for dir in borgbackup_exclude %} --exclude '{{ dir }}'{% endfor %} 
+    BORGEXIT+=($?)
+    
+{% if mysql_installed.stat.isdir is defined and borgbackup_do_mysql == True %}
+    mysqldump -A | /usr/local/bin/borg create --progress --compression {{ borgbackup_compression }} --stats {{ b.options }} $REPOSITORY::mysqldump-$date - 
+    BORGEXIT+=($?)
+{% endif %}
 
-    if [ "$?" -eq "0" ]; then printf "Backup succeeded on $date to {{ b.fqdn }}\n" >> /var/log/borg-backup.log; fi
+    # iterate over exit codes
+    EXITCODE=''
+    for i in ${BORGEXIT[@]}; do
+        ((EXITCODE+=$i))
+    done
 
-  {% if not borgbackup_appendonly %}
-    # prune old backups
+    if [ $EXITCODE -eq 0 ]; then 
+        printf "Backup succeeded on $date to {{ b.fqdn }}\n" >> /var/log/borg-backup.log
+{% if borgbackup_statuscake_url is defined %}
+        curl -sfL "{{borgbackup_statuscake_url}}" --output /dev/null
+{% endif %}
+
+{% if not borgbackup_appendonly %}
+    # prune old backups if we exited correctly
     /usr/local/bin/borg prune {{ b.options }} -v $REPOSITORY -H {{ borgbackup_retention.hourly }} -d {{ borgbackup_retention.daily }} -w {{ borgbackup_retention.weekly }} -m {{ borgbackup_retention.monthly }} -y {{ borgbackup_retention.yearly }}
-  {% endif %}
+{% endif %}
+    else
+        printf "Backup FAILED on $date to {{ b.fqdn }}\n" >> /var/log/borg-backup.log
+    fi
+
 {% endfor %}
 
     # Running some commands post-backup
